 <form method="post" action="index.php">
    
        <label for="email">email</label>
        <input type="email" name="email" id="email" />
        
        <label for="username">username</label>
        <input type="password" name="username" id="username" />
        
        <label for="password">password</label>
        <input type="password" name="password" id="password" />

        <input type="submit" value="Envoyer"/>
</form>